kind = "web"
previewPath = "/"
title = "Prova Island"
version = "1.0.0"
id = "artifacts/prova-island"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22512

[services.development]
run = "pnpm --filter @workspace/prova-island run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/prova-island", "run", "build" ]
publicDir = "artifacts/prova-island/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22512"
BASE_PATH = "/"
